### ISSUE TITLE
Add mypy pre-commit hook

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/kowalski#75]
**Feature Summary**
As suggested by @stefanv, add `mypy` to pre-commit hooks.

**Implementation details**
```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.782'
    hooks:
    -   id: mypy
```
